# This is a basic workflow to help you get started with Actions

name: Build Inquizitor API Image and Deploy to Heroku

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    name: Build and deploy Inquizitor API
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      # https://dev.to/analythium/deploying-shiny-apps-to-heroku-with-docker-and-github-actions-2687
      - name: Build and push Docker to Heroku
        env:
          HEROKU_APP_NAME: inquizitor-test
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          DOCKER_OPTIONS: "--no-cache --force-recreate"
        run: |
          cp .env.example .env
          echo ${HEROKU_API_KEY} | docker login \
            --username=${HEROKU_EMAIL} \
            registry.heroku.com \
            --password-stdin
          docker-compose up -d --build \
            ${DOCKER_OPTIONS} \
            --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
          heroku container:push web --app ${HEROKU_APP_NAME}
          heroku container:release web --app ${HEROKU_APP_NAME}
          heroku ps:scale web=1 --app ${HEROKU_APP_NAME}
